name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
      - name: Configure CMake
        run: |
          cmake -H. -Bbuild -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS='--coverage'
      - name: Build project
        run: |
          cmake --build build

      - name: Run tests
        run: |
          build/tests/check_acc
          build/tests/check_tr

      - name: Generate coverage report
        run: |
          cd build
          lcov -c -d banking/CMakeFiles/account.dir -o account.info
          lcov -c -d banking/CMakeFiles/transaction.dir -o transaction.info
          lcov -a account.info -a transaction.info -o coverage.info
          lcov --extract coverage.info '*/banking/*' -o coverage_filtered.info
          mv coverage_filtered.info coverage.info

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage.info
